type: php
docroot: .Build
additional_hostnames:
  - 13.xima-typo3-frontend-edit
  - 14.xima-typo3-frontend-edit
hooks:
   post-start:
    - exec: mkdir -p /var/www/html/.Build/ && cp -r /var/www/html/.ddev/.setup/templates/. /var/www/html/.Build/ && bash /var/www/html/.ddev/.setup/scripts/write-git-info.sh
